server:
  port: 8083
  servlet:
    context-path: /ui
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: ca590273ed4aacf25d8e
      clientSecret: 87e1e02e6f20adf8253ec8620c5e0ab015f577a5
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
    resource:
      userInfoUri: https://api.github.com/user
